// MA — Maintenance
export default {
  "MA-1": { title:"Policy and Procedures", body:`[ORG] has developed, documented, and disseminated a Maintenance Policy requiring all maintenance to be authorized, documented, and performed by qualified personnel consistent with DoDI 8500.01 and applicable STIGs. Reviewed annually. The [ISSO] approves maintenance activities impacting [SYSTEM] security posture.`, tools:[] },
  "MA-2": { title:"Controlled Maintenance", body:`All maintenance on [SYSTEM] is scheduled, documented, and controlled. Maintenance windows are established and communicated in advance. [ISSO] reviews maintenance requests for security impact before approval. All maintenance actions are logged including date/time, technician identity, nature of maintenance, and results. [TOOL:splunk] monitors system activity during maintenance. Hardware removed for maintenance is sanitized per MP-6. Records retained for 3 years.`, tools:["splunk"] },
  "MA-2(2)": { title:"Controlled Maintenance | Automated Maintenance Activities", body:`[SYSTEM] employs automated mechanisms to schedule, conduct, and document maintenance and repairs. [TOOL:wsus] automates patch maintenance scheduling and deployment for Windows systems. [TOOL:tenablesc] schedules automated vulnerability scans as part of the maintenance program. Automated maintenance activities are logged to [TOOL:splunk] and reviewed by the [ISSO] weekly.`, tools:["wsus","tenablesc","splunk"] },
  "MA-3": { title:"Maintenance Tools", body:`[ORG] controls maintenance tools used on [SYSTEM]. Approved tools are documented and inspected before use. Media containing diagnostic programs is scanned by [TOOL:hbss] before use. [TOOL:crowdstrike] is active during maintenance to detect malicious activity. Personal maintenance equipment is prohibited unless [ISSO] approved. Remote maintenance tools are approved and monitored. Inventory reviewed quarterly.`, tools:["hbss","crowdstrike"] },
  "MA-3(1)": { title:"Maintenance Tools | Inspect Tools", body:`[ORG] inspects maintenance tools used on [SYSTEM] for improper or unauthorized modifications. Maintenance tools are inspected visually and scanned by [TOOL:hbss] before use. Media containing diagnostic software is scanned before connecting to [SYSTEM]. [TOOL:crowdstrike] monitors for malicious activity from connected maintenance tools. Inspection results are documented in the maintenance log.`, tools:["hbss","crowdstrike"] },
  "MA-3(2)": { title:"Maintenance Tools | Inspect Media", body:`[ORG] checks maintenance media containing diagnostic and test programs for malicious code before using on [SYSTEM]. All portable media used for maintenance is scanned by [TOOL:hbss] before connecting to [SYSTEM] components. [TOOL:crowdstrike] provides additional scanning on any media connected during maintenance. Media that fails scanning is quarantined and reported to the [ISSO].`, tools:["hbss","crowdstrike"] },
  "MA-3(3)": { title:"Maintenance Tools | Prevent Unauthorized Removal", body:`[ORG] prevents the removal of maintenance equipment containing organizational information by verifying maintenance equipment is free of organizational information before removal. Before removing maintenance equipment, system administrators verify no CUI or [SYSTEM] data resides on the equipment. [TOOL:hbss] and [TOOL:crowdstrike] scan maintenance media before removal. Removal of maintenance equipment is documented in the maintenance log.`, tools:["hbss","crowdstrike"] },
  "MA-4": { title:"Nonlocal Maintenance", body:`Remote maintenance conducted through [TOOL:ivanti] VPN with [TOOL:cac] authentication. All remote maintenance sessions are monitored and logged to [TOOL:splunk]. [ISSO] approves all remote maintenance before execution. Remote maintenance terminated immediately upon completion. Vendor maintenance requires [ISSO] presence and real-time monitoring. All sessions documented in the maintenance log.`, tools:["ivanti","cac","splunk"] },
  "MA-4(2)": { title:"Nonlocal Maintenance | Document Nonlocal Maintenance", body:`[ORG] documents nonlocal maintenance and diagnostic activities for [SYSTEM]. All remote maintenance sessions are documented including: date/time, duration, technician identity, systems accessed, actions taken, and results. [TOOL:splunk] provides automated session logging. Documentation is retained in the maintenance log for 3 years. The [ISSO] reviews remote maintenance logs monthly.`, tools:["splunk"] },
  "MA-4(3)": { title:"Nonlocal Maintenance | Comparable Security", body:`[ORG] requires the implementation of security controls on systems used for nonlocal maintenance and diagnostic activities equivalent to those implemented on [SYSTEM]. Remote maintenance systems must have [TOOL:crowdstrike] installed and active. Remote maintenance systems connect exclusively via [TOOL:ivanti] VPN. [TOOL:cac] authentication is required. Maintenance system compliance is verified by the [ISSO] before session authorization.`, tools:["crowdstrike","ivanti","cac"] },
  "MA-4(6)": { title:"Nonlocal Maintenance | Cryptographic Protection", body:`[SYSTEM] implements cryptographic mechanisms to protect integrity and confidentiality of nonlocal maintenance and diagnostic communications. [TOOL:ivanti] VPN uses AES-256 encryption for all remote maintenance sessions. TLS 1.2 or higher is required for web-based maintenance interfaces. [TOOL:paloalto] enforces encryption requirements for remote maintenance traffic. Cryptographic protection compliance is validated via [TOOL:stig].`, tools:["ivanti","paloalto","stig"] },
  "MA-5": { title:"Maintenance Personnel", body:`Only personnel with appropriate background investigations and access authorizations perform maintenance. Vendor maintenance personnel are escorted by [ORG] personnel with equivalent clearances. [ISSO] maintains list of authorized maintenance personnel reviewed quarterly. Maintenance personnel authenticate via [TOOL:cac]. Temporary maintenance accounts are removed immediately after completion.`, tools:["cac"] },
  "MA-5(1)": { title:"Maintenance Personnel | Individuals Without Appropriate Access", body:`[ORG] implements procedures for maintenance by personnel without required clearances or access authorizations. Uncleared maintenance personnel are continuously escorted by cleared [ORG] personnel during maintenance. All information that the uncleared personnel can access is sanitized before maintenance or protected during maintenance. The [ISSO] approves uncleared maintenance access on a case-by-case basis with documented rationale.`, tools:[] },
  "MA-6": { title:"Timely Maintenance", body:`[ORG] obtains maintenance support and spare parts for [SYSTEM] within [MAINTENANCE TIMEFRAME] of failure. Spare parts inventory for critical components is maintained. Maintenance contracts with vendors are in place. [ISSM] notified when maintenance cannot be completed within required timeframes. Alternative processing per CP is activated when maintenance exceeds tolerable outage.`, tools:[] },
};
