// PS — Personnel Security
export default {
  "PS-1": { title:"Policy and Procedures", body:`[ORG] has developed, documented, and disseminated a Personnel Security Policy consistent with DoDI 5200.02 and applicable DoD personnel security policy. Requires background investigation commensurate with access level. Reviewed annually. The [ISSM] coordinates with Personnel Security Officer on personnel security requirements for [SYSTEM].`, tools:[] },
  "PS-2": { title:"Position Risk Designation", body:`[ORG] assigns risk designations to all positions with access to [SYSTEM]. Positions are designated based on sensitivity of data accessed and potential for harm. [SYSTEM] positions require minimum [CLEARANCE LEVEL] security clearance. Position risk designations are documented in position descriptions and reviewed when positions change. Personnel Security Officer coordinates with [ISSO] on risk designation requirements.`, tools:[] },
  "PS-3": { title:"Personnel Screening", body:`[ORG] screens individuals prior to authorizing access to [SYSTEM]. All personnel with access must have minimum [CLEARANCE LEVEL] security clearance from DCSA or appropriate clearance authority. Background investigations are commensurate with the risk designation of the position. [ISSO] verifies clearance status before creating [SYSTEM] accounts. Clearance status reverified annually. Personnel Security Officer notifies [ISSO] immediately of clearance revocations or adverse actions.`, tools:[] },
  "PS-3(3)": { title:"Personnel Screening | Information with Special Protection Measures", body:`[ORG] ensures personnel with access to [SYSTEM] information requiring special protection measures (CUI, SAP, SCI) have appropriate access authorizations and need-to-know. Access to specialized information requires specific authorization beyond the baseline security clearance. The [ISSO] verifies special access authorizations before granting access to restricted information types. Special access authorizations are tracked by the Personnel Security Officer and reviewed quarterly.`, tools:[] },
  "PS-4": { title:"Personnel Termination", body:`[ORG] terminates [SYSTEM] access for personnel upon separation within 24 hours of notification. [TOOL:ad] accounts are disabled and credentials invalidated. [TOOL:cac] access is revoked via DoD PKI revocation. [TOOL:ivanti] VPN access is removed. Separation checklists ensure all access is revoked. [ISSO] conducts exit interviews emphasizing data handling responsibilities. Separation notifications sent to [ISSM].`, tools:["ad","cac","ivanti"] },
  "PS-4(2)": { title:"Personnel Termination | Automated Notification", body:`[SYSTEM] employs automated mechanisms to notify [ISSO] upon personnel termination. HR system integration provides automated notification to the [ISSO] when personnel separation is processed. [TOOL:splunk] monitors for account activity after termination notification and alerts the [ISSO] to any access attempts. Automated termination checklists ensure all [SYSTEM] access is revoked within 24 hours.`, tools:["splunk"] },
  "PS-5": { title:"Personnel Transfer", body:`[ORG] reviews [SYSTEM] access authorizations when personnel are transferred or reassigned. [ISSO] reviews and adjusts access within 5 business days of notification. Accounts no longer needed are disabled. Access updated to reflect new role (least privilege). [TOOL:ad] group memberships updated per new role. [ISSO] documents access changes and notifies [ISSM] of significant access modifications.`, tools:["ad"] },
  "PS-6": { title:"Access Agreements", body:`[ORG] requires personnel with access to [SYSTEM] to sign access agreements including Rules of Behavior (ROB) and appropriate NDAs. Access agreements are signed before account creation and annually thereafter. Signed agreements maintained by [ISSO] for duration of access plus 3 years. Access is revoked for personnel who refuse to sign or violate terms. [ISSO] tracks compliance and reports to [ISSM] quarterly.`, tools:[] },
  "PS-7": { title:"External Personnel Security", body:`[ORG] establishes personnel security requirements for external service providers supporting [SYSTEM]. Contractors must have appropriate security clearances verified by [ISSO] before access. Contractor access is limited to the scope of the service contract. [TOOL:cac]-based authentication is required for contractor accounts. Contractor accounts are reviewed quarterly and removed upon contract completion.`, tools:["cac"] },
  "PS-8": { title:"Personnel Sanctions", body:`[ORG] employs a formal sanctions process for personnel who violate [SYSTEM] security policies. Violations are reported to the individual's supervisor and [ISSM]. Sanctions range from verbal counseling to termination depending on severity. Security violations are documented and factored into future access authorization decisions. [ISSO] maintains a log of security violations and sanctions for [SYSTEM].`, tools:[] },
  "PS-9": { title:"Position Descriptions", body:`[ORG] establishes and documents security roles, responsibilities, and procedures for positions with significant security responsibilities for [SYSTEM]. Position descriptions for [ISSO], [ISSM], and system administrators document security responsibilities. Position descriptions are reviewed and updated when security responsibilities change. The [ISSM] verifies position descriptions accurately reflect security requirements annually.`, tools:[] },
};
