// RA — Risk Assessment
export default {
  "RA-1": { title:"Policy and Procedures", body:`[ORG] has developed, documented, and disseminated a Risk Assessment Policy consistent with NIST SP 800-30 and DoD risk management guidance. Requires annual risk assessments for [SYSTEM]. Reviewed annually. The [ISSO] conducts risk assessments in coordination with [ISSM].`, tools:[] },
  "RA-2": { title:"Security Categorization", body:`[SYSTEM] has been categorized per FIPS 199 and CNSSI 1253 as [SECURITY CATEGORIZATION]. The categorization considers confidentiality, integrity, and availability impact on operations, assets, and individuals. Information types processed include [INFORMATION TYPES]. Documented in the SSP maintained in [TOOL:emass] and reviewed annually. [AO] approved the security categorization as part of the authorization decision.`, tools:["emass"] },
  "RA-3": { title:"Risk Assessment", body:`[ORG] conducts risk assessments for [SYSTEM] annually and after significant changes. Risk assessments incorporate: [TOOL:acas]/[TOOL:tenablesc] vulnerability data, [TOOL:scap] STIG compliance results, [TOOL:crowdstrike] threat intelligence, penetration test findings, and [TOOL:splunk] continuous monitoring data. Assessed using NIST SP 800-30 methodology. Results documented and provided to [ISSM] and [AO]. Identified risks drive POAM entries in [TOOL:emass].`, tools:["acas","tenablesc","scap","crowdstrike","splunk","emass"] },
  "RA-3(1)": { title:"Risk Assessment | Supply Chain Risk Assessment", body:`[ORG] assesses supply chain risks associated with [SYSTEM] as part of the organizational risk assessment. Supply chain risk assessment addresses: hardware and software suppliers, development practices, delivery mechanisms, and maintenance support. Critical components identified in CM-12 receive focused supply chain risk analysis. Supply chain risks are documented and addressed in the SCRM Plan per SR-2. The [ISSM] reviews supply chain risk assessment results annually.`, tools:[] },
  "RA-3(2)": { title:"Risk Assessment | Use of All-Source Intelligence", body:`[ORG] uses all-source intelligence to assess [SYSTEM] risks. Intelligence sources include: [TOOL:crowdstrike] threat intelligence, CISA Alerts and Advisories, DoD Cyber tasking orders, US-CERT notifications, and applicable ISAC threat reports. Intelligence is analyzed by the [ISSO] to identify threats relevant to [SYSTEM]. Threat intelligence findings are incorporated into risk assessments and drive proactive defensive measures.`, tools:["crowdstrike"] },
  "RA-5": { title:"Vulnerability Monitoring and Scanning", body:`Vulnerability scanning using [TOOL:acas] managed by [TOOL:tenablesc]: weekly network/OS scans, monthly database scans, quarterly web application scans. Authenticated scanning maximizes coverage. Results reviewed by [ISSO] within 5 business days. CAT I: 30-day remediation; CAT II: 90-day; CAT III: 180-day. Unresolved findings in POAM in [TOOL:emass]. [TOOL:scap] provides quarterly STIG compliance scanning. [TOOL:crowdstrike] Spotlight provides continuous CVE-to-asset mapping. Patches managed via [TOOL:wsus].`, tools:["acas","tenablesc","emass","scap","crowdstrike","wsus","stig"] },
  "RA-5(1)": { title:"Vulnerability Monitoring | Update Vulnerabilities Scanned", body:`[ORG] updates the list of information system vulnerabilities scanned for [SYSTEM] before each scan and when new vulnerabilities are identified. [TOOL:tenablesc] plugin feeds update [TOOL:acas] scanner plugin databases automatically within 24 hours of availability. [TOOL:scap] content (XCCDF checklists, OVAL definitions) is updated within 30 days of DISA releases. [TOOL:crowdstrike] threat intelligence provides continuous vulnerability intelligence updates.`, tools:["tenablesc","acas","scap","crowdstrike"] },
  "RA-5(2)": { title:"Vulnerability Monitoring | Update by Frequency and Prior to New Scans", body:`[ORG] updates the system vulnerabilities scanned prior to each scan and when new vulnerabilities are identified and reported. [TOOL:tenablesc] is configured to automatically update [TOOL:acas] plugins before initiating scans. Scan schedules allow sufficient time for plugin updates before scan execution. Plugin currency is verified before each scan and discrepancies are reported to the [ISSO].`, tools:["tenablesc","acas"] },
  "RA-5(4)": { title:"Vulnerability Monitoring | Discoverable Information", body:`[ORG] determines what information about [SYSTEM] is discoverable by adversaries. [TOOL:acas] external-perspective scans identify information visible from outside the boundary. [TOOL:paloalto] external-facing rule review identifies unnecessarily exposed services. The [ISSO] reviews discoverable information quarterly. Unnecessarily exposed information is addressed through firewall rule changes and CCB-approved configuration modifications.`, tools:["acas","paloalto"] },
  "RA-5(5)": { title:"Vulnerability Monitoring | Privileged Access", body:`[ORG] implements privileged access authorization for authenticated vulnerability scanning. [TOOL:acas] uses privileged scanning credentials for authenticated assessment of all [SYSTEM] components. Authenticated scanning provides significantly more complete vulnerability coverage than unauthenticated scanning. Scanning credentials are stored securely in [TOOL:tenablesc] credential management. Scanning credential access is restricted to [ISSO]-authorized personnel.`, tools:["acas","tenablesc"] },
  "RA-5(11)": { title:"Vulnerability Monitoring | Public Disclosure Program", body:`[ORG] establishes a vulnerability disclosure program for [SYSTEM]. The vulnerability disclosure program provides a mechanism for external researchers to report vulnerabilities. Reported vulnerabilities are assessed by the [ISSO] within 5 business days. Validated vulnerabilities are tracked in the POAM in [TOOL:emass] with appropriate remediation timelines. The [ISSM] reviews the vulnerability disclosure program annually.`, tools:["emass"] },
  "RA-7": { title:"Risk Response", body:`[ORG] responds to identified risks to [SYSTEM] through a structured risk response process. Risk response options include: accept, avoid, mitigate, share, or transfer. Risk acceptance decisions are documented and approved by [AO]. Mitigation actions tracked in POAM in [TOOL:emass]. [ISSM] reviews risk response decisions quarterly. Residual risk is documented in the authorization decision.`, tools:["emass"] },
  "RA-9": { title:"Criticality Analysis", body:`[ORG] identifies critical [SYSTEM] components and functions through a criticality analysis. Critical components are identified based on: mission impact of failure, difficulty of replacement, supply chain risk, and adversary targeting value. Criticality analysis results inform security control selection, supply chain risk management, and contingency planning. Analysis is reviewed annually and when significant changes occur.`, tools:[] },
  "RA-10": { title:"Threat Modeling", body:`[ORG] performs threat modeling for [SYSTEM] to identify threats, vulnerabilities, and corresponding mitigations. Threat modeling methodology follows applicable DoD and NIST guidance. Threats are identified using [TOOL:crowdstrike] threat intelligence and DoD cyber threat briefings. Threat model results inform control selection, architecture decisions, and penetration test planning. Threat models are reviewed annually and updated when significant changes occur or new threat information becomes available.`, tools:["crowdstrike"] },
};
